# Generated by Django 5.0.7 on 2024-07-15 08:41

import app_authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0003_rename_username_customuser_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_expiry',
            field=models.DateTimeField(default=app_authentication.models.default_expiry),
        ),
    ]
