# Generated by Django 5.0.7 on 2024-08-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_videoflix', '0002_globalvideo_thumbnail_localvideo_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalvideo',
            name='is_local',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='localvideo',
            name='is_local',
            field=models.BooleanField(default=True),
        ),
    ]
