# Generated by Django 5.0.7 on 2024-09-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_videoflix', '0003_globalvideo_is_local_localvideo_is_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='localvideo',
            name='thumbnail_created',
            field=models.BooleanField(default=False),
        ),
    ]
